spring:
  application:
    name: mqttx-platform
  profiles:
    active: @profile@
  liquibase:
    change-log: classpath:db/master.xml
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true

